
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Wed Mar 15 17:49:01 EDT 2023
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class A4Symbol {
  /* terminals */
  public static final int TIMES = 4;
  public static final int READ = 10;
  public static final int SEMICOLON = 26;
  public static final int ELSE = 13;
  public static final int PLUS = 2;
  public static final int INT = 19;
  public static final int RPAREN = 8;
  public static final int EQUAL = 6;
  public static final int NOTEQUAL = 27;
  public static final int Float = 23;
  public static final int END = 16;
  public static final int RETURN = 14;
  public static final int Integer = 21;
  public static final int IF = 12;
  public static final int COLON = 25;
  public static final int LPAREN = 7;
  public static final int WRITE = 11;
  public static final int ID = 9;
  public static final int BEGIN = 15;
  public static final int STRING = 18;
  public static final int COMMA = 24;
  public static final int EOF = 0;
  public static final int DIVIDE = 5;
  public static final int MAIN = 17;
  public static final int MINUS = 3;
  public static final int error = 1;
  public static final int ASSIGN = 28;
  public static final int QSTRING = 22;
  public static final int REAL = 20;
}

